name: Multi Lang App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages (native + .NET)
        run: nuget restore DotNetSolution\DotNetSolution.sln

      - name: Build Cpp Project
        run: msbuild DotNetSolution\CppProject\CppProject.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Build C++ Test Project
        run: msbuild DotNetSolution\Tests\CppNativeTests\CppNativeTests.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Run C++ Google Tests
        run: |
          mkdir CppTestResults
          .\DotNetSolution\Tests\CppNativeTests\x64\Release\CppNativeTests.exe --gtest_output=xml:CppTestResults\CppTestResults.xml

      - name: Upload C++ Test Results
        uses: actions/upload-artifact@v4
        with:
          name: cpp-test-results
          path: CppTestResults/

      - name: Build CLI Project
        run: msbuild DotNetSolution\CliProject\CliProject.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Build CLI Test Project
        run: msbuild DotNetSolution\Tests\CliTests\CliTests.csproj /p:Configuration=Release /p:Platform=x64

      - name: Run CLI Tests
        shell: bash
        run: |
          dotnet test DotNetSolution/Tests/CliTests/CliTests.csproj \
            --configuration Release \
            --no-build \
            --logger trx \
            --results-directory CliTestResults

      - name: Publish CLI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: cli-results
          path: CliTestResults/

      - name: Build Wpf Application
        run: msbuild DotNetSolution\WpfApp\WpfApp.csproj /p:Configuration=Release

      - name: Build .NET Standard Project
        run: msbuild DotNetSolution\NetStandardLib\NetStandardLib.csproj /p:Configuration=Release

      - name: Build .NET Framework Project
        run: msbuild DotNetSolution\NetFrameworkApp\NetFrameworkApp.csproj /p:Configuration=Release

      - name: Build .NET Test Project
        run: msbuild DotNetSolution\Tests\DotNetTests\DotNetTests.csproj /p:Configuration=Release

      - name: Run .NET Tests
        shell: bash
        run: |
          dotnet test DotNetSolution/Tests/DotNetTests/DotNetTests.csproj \
            --configuration Release \
            --no-build \
            --logger trx \
            --results-directory DotNetTestResults

      - name: Publish .NET Test Results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: DotNetTestResults/

      - name: Build Wpf Application
        run: msbuild DotNetSolution\WpfApp\WpfApp.csproj /p:Configuration=Release  /p:Platform=x64
