name: Multi Lang App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install WiX Toolset 3.14
        run: choco install wixtoolset --version=3.14.1.20250415 --yes

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: msbuild DotNetSolution\DotNetSolution.sln /t:Restore

      - name: Install Intel OneAPI Base & HPC Toolkit
        shell: cmd
        run: |
          curl -L -o basekit.exe https://registrationcenter-download.intel.com/akdlm/IRC_NAS/09a8acaf-265f-4460-866c-a3375ed5b4ff/intel-oneapi-base-toolkit-2025.2.0.591_offline.exe
          curl -L -o hpckit.exe https://registrationcenter-download.intel.com/akdlm/IRC_NAS/3bbdaf75-6728-492e-a18c-be654dae9ee2/intel-oneapi-hpc-toolkit-2025.2.0.576_offline.exe
          basekit.exe --silent --eula accept --a --components=intel.oneapi.win.ifort-compiler
          hpckit.exe  --silent --eula accept --a --components=intel.oneapi.win.ifort-compiler

      - name: Build Fortran Solution
        shell: cmd
        run: |
          :: set up Intel OneAPI environment
          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
          :: go to workspace
          cd %GITHUB_WORKSPACE%
          devenv.com FortranSolution\FortranSolution.sln /Build "Release|x64"

      - name: Build DotNet Solution
        run: msbuild DotNetSolution\DotNetSolution.sln /p:Configuration=Release

      - name: Build MSI Installer
        run: msbuild Installer\Installer.sln /p:Configuration=Release /p:Platform=x86

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MSI-Package
          path: |
            Installer\bin\Release\*.msi
            Installer\bin\Release\*.cab
