name: Multi Lang App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install WiX Toolset 3.14
        run: choco install wixtoolset --version=3.14.1.20250415 --yes

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages (native + .NET)
        run: nuget restore DotNetSolution\DotNetSolution.sln

      - name: Build .NET Solution
        run: msbuild DotNetSolution\DotNetSolution.sln /p:Configuration=Release

      - name: Run .NET Tests
        shell: bash
        run: |
          dotnet test DotNetSolution/Tests/DotNetTests/DotNetTests.csproj \
            --configuration Release \
            --no-build \
            --logger trx \
            --results-directory DotNetTestResults

      - name: Publish .NET Test Results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: DotNetTestResults/

      - name: Run C++ Google Tests
        run: |
          mkdir CppTestResults
          .\DotNetSolution\Tests\CppNativeTests\x64\Release\CppNativeTests.exe --gtest_output=xml:CppTestResults\CppTestResults.xml

      - name: Upload C++ Test Results
        uses: actions/upload-artifact@v4
        with:
          name: cpp-test-results
          path: CppTestResults/
